### ISSUE TITLE
Installing content pack failed

### ISSUE THREAD

**Issue by Kofl** [ntimo/graylog-mailcow-content-pack#12]
Hi,

having no luck installing the content pack on the current graylog release:

`Installing content pack failed with status: FetchError: There was an error fetching a resource: Internal Server Error. Additional information: Failed to install content pack <e47c37bf-86ad-405f-80c1-5c26ef8464fe/17>. Could not install Content Pack with ID: e47c37bf-86ad-405f-80c1-5c26ef8464fe`

Error log:

Probably thats the cause?

Caused by: org.graylog2.contentpacks.exceptions.ContentPackException: Missing Stream for widget entity

```
2023-04-18 20:02:42,909 INFO : org.mongodb.driver.connection - Opened connection [connectionId{localValue:60, serverValue:25}] to mongodb:27017
18/04/2023 22:02:42
2023-04-18 20:02:42,914 INFO : org.mongodb.driver.connection - Opened connection [connectionId{localValue:59, serverValue:24}] to mongodb:27017
18/04/2023 22:02:43
2023-04-18 20:02:43,084 INFO : org.graylog2.lookup.LookupTableService - Data Adapter geo-ip-city-maxmind-adapater/643ef76319b7ce03047ce0bb [@1234c437] STARTING
18/04/2023 22:02:43
2023-04-18 20:02:43,098 INFO : org.graylog2.lookup.LookupTableService - Data Adapter geo-ip-city-maxmind-adapater/643ef76319b7ce03047ce0bb [@1234c437] RUNNING
18/04/2023 22:02:43
2023-04-18 20:02:43,099 INFO : org.graylog2.lookup.LookupDataAdapterRefreshService - Adding job for <geo-ip-city-maxmind-adapater/643ef76319b7ce03047ce0bb/@1234c437> [interval=86400000ms]
18/04/2023 22:02:43
2023-04-18 20:02:43,358 INFO : org.graylog2.lookup.LookupTableService - Cache geo-ip-city-maxmind-cache/643ef76319b7ce03047ce0d8 [@52a078e4] STARTING
18/04/2023 22:02:43
2023-04-18 20:02:43,364 INFO : org.graylog2.lookup.LookupTableService - Cache geo-ip-city-maxmind-cache/643ef76319b7ce03047ce0d8 [@52a078e4] RUNNING
18/04/2023 22:02:43
2023-04-18 20:02:43,548 INFO : org.graylog2.lookup.LookupTableService - Cache geo-ip-city-maxmind-cache/643ef76319b7ce03047ce0d8 [@52a078e4] STOPPING, was RUNNING
18/04/2023 22:02:43
2023-04-18 20:02:43,554 INFO : org.graylog2.lookup.LookupTableService - Cache geo-ip-city-maxmind-cache/643ef76319b7ce03047ce0d8 [@52a078e4] TERMINATED, was STOPPING
18/04/2023 22:02:43
2023-04-18 20:02:43,643 INFO : org.graylog2.lookup.LookupTableService - Data Adapter geo-ip-city-maxmind-adapater/643ef76319b7ce03047ce0bb [@1234c437] STOPPING, was RUNNING
18/04/2023 22:02:43
2023-04-18 20:02:43,643 INFO : org.graylog2.lookup.LookupDataAdapterRefreshService - Removing job for <geo-ip-city-maxmind-adapater/643ef76319b7ce03047ce0bb/@1234c437>
18/04/2023 22:02:43
2023-04-18 20:02:43,645 INFO : org.graylog2.lookup.LookupTableService - Data Adapter geo-ip-city-maxmind-adapater/643ef76319b7ce03047ce0bb [@1234c437] TERMINATED, was STOPPING
18/04/2023 22:02:43
2023-04-18 20:02:43,968 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
18/04/2023 22:02:43
org.graylog2.contentpacks.exceptions.ContentPackException: Failed to install content pack <e47c37bf-86ad-405f-80c1-5c26ef8464fe/17>
18/04/2023 22:02:43
	at org.graylog2.contentpacks.ContentPackService.installContentPack(ContentPackService.java:161) ~[graylog.jar:?]
18/04/2023 22:02:43
	at org.graylog2.contentpacks.ContentPackService.installContentPack(ContentPackService.java:102) ~[graylog.jar:?]
18/04/2023 22:02:43
	at org.graylog2.rest.resources.system.contentpacks.ContentPackResource.installContentPack(ContentPackResource.java:295) ~[graylog.jar:?]
18/04/2023 22:02:43
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
18/04/2023 22:02:43
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[graylog.jar:?]
18/04/2023 22:02:43
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134) ~[graylog.jar:?]
18/04/2023 22:02:43
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177) ~[graylog.jar:?]
18/04/2023 22:02:43
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[graylog.jar:?]
18/04/2023 22:02:43
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81) ~[graylog.jar:?]
18/04/2023 22:02:43
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[graylog.jar:?]
18/04/2023 22:02:43
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[graylog.jar:?]
18/04/2023 22:02:43
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[graylog.jar:?]
18/04/2023 22:02:43
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [graylog.jar:?]
18/04/2023 22:02:43
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [graylog.jar:?]
18/04/2023 22:02:43
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [graylog.jar:?]
18/04/2023 22:02:43
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [graylog.jar:?]
18/04/2023 22:02:43
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [graylog.jar:?]
18/04/2023 22:02:43
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [graylog.jar:?]
18/04/2023 22:02:43
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [graylog.jar:?]
18/04/2023 22:02:43
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [graylog.jar:?]
18/04/2023 22:02:43
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) [graylog.jar:?]
18/04/2023 22:02:43
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [graylog.jar:?]
18/04/2023 22:02:43
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [graylog.jar:?]
18/04/2023 22:02:43
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
18/04/2023 22:02:43
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
18/04/2023 22:02:43
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
18/04/2023 22:02:43
	at java.lang.Thread.run(Unknown Source) [?:?]
18/04/2023 22:02:43
Caused by: org.graylog2.contentpacks.exceptions.ContentPackException: Missing Stream for widget entity
18/04/2023 22:02:43
	at org.graylog2.contentpacks.model.entities.WidgetEntity.lambda$toNativeEntity$1(WidgetEntity.java:162) ~[graylog.jar:?]
18/04/2023 22:02:43
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at org.graylog2.contentpacks.model.entities.WidgetEntity.toNativeEntity(WidgetEntity.java:170) ~[graylog.jar:?]
18/04/2023 22:02:43
	at org.graylog2.contentpacks.model.entities.ViewStateEntity.lambda$toNativeEntity$0(ViewStateEntity.java:125) ~[graylog.jar:?]
18/04/2023 22:02:43
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
18/04/2023 22:02:43
	at org.graylog2.contentpacks.model.entities.ViewStateEntity.toNativeEntity(ViewStateEntity.java:126) ~[graylog.jar:?]
18/04/2023 22:02:43
	at org.graylog2.contentpacks.facades.ViewFacade.decode(ViewFacade.java:137) ~[graylog.jar:?]
18/04/2023 22:02:43
	at org.graylog2.contentpacks.facades.ViewFacade.createNativeEntity(ViewFacade.java:127) ~[graylog.jar:?]
18/04/2023 22:02:43
	at org.graylog2.contentpacks.ContentPackService.installContentPack(ContentPackService.java:152) ~[graylog.jar:?]
18/04/2023 22:02:43
	... 29 more
```

**Comment by Kofl** [comment]
Removed all widget, so the import could finish:

entities state titles => widget

**Comment by Kofl** [comment]
but lookup lookup_table and pipelines are missing, so its at the end unusable :-/

**Comment by Kofl** [comment]
but lookup lookup_table and pipelines are missing, so its at the end unusable :-/

Import with higher revision and original file then worked fine, very strange.

Trying to generate a CR necessary for the docker container name changes.
